apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helloworld
  name: helloworld
  namespace: helloworld
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - image: trendev/helloworld
          imagePullPolicy: Always
          name: helloworld
          ports:
            - containerPort: 8080
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: RECORDS_MAX_SIZE
              value: "30"
            - name: TEXT_MESSAGE
              value: "Hello Kubernetes World"
          args:
            - "--clustermode"
            - "kubernetes:$(MY_POD_NAMESPACE),helloworld"
            - "--group"
            - "ig_$(MY_POD_NAMESPACE)" 
            - "--clustername" 
            - "dg_$(MY_POD_NAMESPACE)"
            - "--deploymentDir"
            - "/opt/payara/deployments"
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 2
            failureThreshold: 1
          # version 1.16 - alpha
          # startupProbe:
          #   httpGet:
          #     path: /health/live
          #     port: 8080
          #   failureThreshold: 12
          #   periodSeconds: 5
          #   initialDelaySeconds: 20
          resources: {}
