apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-java
  name: hello-world-java
  namespace: hello-world-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-java
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world-java
    spec:
      containers:
      - image: trendev/hello-world-java        
        imagePullPolicy: Always
        name: hello-world-java
        ports:
        - containerPort: 8080
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: TEXT_MESSAGE
          value: 'Hello Kubernetes World'
        resources: {}