kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: simdg-restriction
  namespace: simdg
spec:
  podSelector: {}
  ingress:
    - ports:
      - port: 8080
      from: []
    - from:
        - podSelector: 
            matchLabels:
              app: simdg
