apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  type: NodePort
  ports:
  - name: http-listener-1
    port: 80
    targetPort: 8080
  selector:
    app: helloworld
