apiVersion: v1
kind: Service
metadata:
  name: simdg
  namespace: simdg
  labels:
    app: simdg
spec:
  type: NodePort
  ports:
  - name: http-listener-1
    port: 80
    targetPort: 8080
  selector:
    app: simdg
